### ISSUE TITLE
v0.7.5 pihole-v6 nil pointer evaluating *glance.dnsStats.TotalQueries

### ISSUE THREAD

**Issue by lukpep** [glanceapp/glance#433]
### Description

config:

```
  - type: dns-stats
    service: pihole-v6
    url: https://pihole.in.xxx.xx
    password: yyyyzyzzyyz
```

gives:

> ERROR Failed to render template error="template: dns-stats.html:7:58: executing \"widget-content\" at <.Stats.TotalQueries>: nil pointer evaluating *glance.dnsStats.TotalQueries"

pihole - latest: 
Docker Tag [2025.03.0](https://github.com/pi-hole/docker-pi-hole/releases/2025.03.0)Core [v6.0.5](https://github.com/pi-hole/pi-hole/releases/v6.0.5)FTL [v6.0.4](https://github.com/pi-hole/FTL/releases/v6.0.4)Web interface [v6.0.2](https://github.com/pi-hole/web/releases/v6.0.2)

Glance:
fresh v0.7.5

![Image](https://github.com/user-attachments/assets/6f6c893e-dcab-47f9-b50c-908738888206)

was waiting for the bug fix so i tried if right away :(

**Comment by svilenmarkov** [comment]
Thanks for the quick report on this one, I'll have a look. Have you possibly changed any settings? I had no issues with a clean installation.

**Comment by AlexStephenLytton** [comment]
I also get the same error... Glance in Docker Container on Unraid 7.0.0, PiHole Core [v6.0.5], FTL [v6.0.4], Web interface [v6.0.2], App Password configured

**Comment by svilenmarkov** [comment]
Should be fixed now, sorry about that, it was due to a last minute change. Let me know if there's any other issues and thanks for reporting the issue so quickly.

**Comment by lukpep** [comment]
works like a charm with 0.7.6

![Image](https://github.com/user-attachments/assets/06f63500-b166-4553-ac60-ae08265bc049)

**Comment by AlexStephenLytton** [comment]
Still getting an error: fetching session ID: authentication response returned empty session ID :(

**Comment by lukpep** [comment]
![Image](https://github.com/user-attachments/assets/d5ee2657-2dda-4a89-9516-97eb1bdadaab)

**Comment by AlexStephenLytton** [comment]
Using Google Chrome on Windows 11... Response is

Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.188.6:80...
* Connected to 192.168.188.6 (192.168.188.6) port 80
* using HTTP/1.x
> POST /api/auth HTTP/1.1
> Host: 192.168.188.6
> User-Agent: curl/8.11.1
> Accept: */*
> Content-Length: 59
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 59 bytes
< HTTP/1.1 200 OK
< Cache-Control: no-cache, no-store, must-revalidate, private, max-age=0
< Expires: 0
< Pragma: no-cache
< Content-Security-Policy: default-src 'self' 'unsafe-inline';
< X-Frame-Options: DENY
< X-XSS-Protection: 0
< X-Content-Type-Options: nosniff
< Referrer-Policy: strict-origin-when-cross-origin
< Access-Control-Allow-Headers: *
< Access-Control-Allow-Methods: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 125
< Date: Sat, 15 Mar 2025 20:34:39 GMT
< Connection: close
< 
* shutting down connection #0

Trying to figure out why password is incorrect.....

**Comment by AlexStephenLytton** [comment]
Renewed App-Password in PiHole, Glance and the Post Request, but still the same error

**Comment by svilenmarkov** [comment]
@lukpep Thanks, I think I have a fix for that now.

@AlexStephenLytton How on earth is it returning a status code 200 with that response message 😆. The entire time I was testing it consistently returned 401 when the password was incorrect. 

Could you also try using your dashboard's password? It could be a problem specific to the app password.

**Comment by AlexStephenLytton** [comment]
Haven't set a dashboard password yet, give me a minute :)

**Comment by AlexStephenLytton** [comment]
Seems like the problem is with App Password - have set a dashboard pw, set that in the glance config and now it seems to work

**Comment by sdr19** [comment]
Was reading through this issue, I'm also having the an issue with 'fetching session ID'

![Image](https://github.com/user-attachments/assets/2a22e15b-b5e5-4857-be53-5ab1c4bcdf75)

I ran 
`curl -v -X POST "http://10.0.19.81/api/auth" --data '{"password":"my-pass"}'`

and got this output
`Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 10.0.19.81:80...
* Connected to 10.0.19.81 (10.0.19.81) port 80
> POST /api/auth HTTP/1.1
> Host: 10.0.19.81
> User-Agent: curl/8.9.1
> Accept: */*
> Content-Length: 24
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 24 bytes
< HTTP/1.1 200 OK
< Cache-Control: no-cache, no-store, must-revalidate, private, max-age=0
< Expires: 0
< Pragma: no-cache
< Content-Security-Policy: default-src 'self' 'unsafe-inline';
< X-Frame-Options: DENY
< X-XSS-Protection: 0
< X-Content-Type-Options: nosniff
< Referrer-Policy: strict-origin-when-cross-origin
< Set-Cookie: sid=a2axeOWAPw2+sf4xS/DH+g=; SameSite=Strict; Path=/; Max-Age=1800; HttpOnly
< Access-Control-Allow-Headers: *
< Access-Control-Allow-Methods: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 176
< Date: Sat, 15 Mar 2025 23:37:03 GMT
< Connection: close
<
{"session":{"valid":true,"totp":false,"sid":"a2axeOWAPw2+sf4xS/DH+g=","csrf":"RrP8LBfaM48xK/fufSn1cw=","validity":1800,"message":"password correct"},"took":0.36159610748291016}* shutting down connection #0`

I tried both the dashboard password and an app password and it had no change.

**Comment by svilenmarkov** [comment]
@sdr19 The output looks correct, did you use `http://10.0.19.81/` for the `url` in the widget?

**Comment by sdr19** [comment]
I feel silly, I forgot the trailing / at the end the url. Thank you so much!
